#!/bin/bash

get_resolution() {
  xdpyinfo | grep dimensions | sed -E 's/.*dimensions:\s+([0-9]+x[0-9]+).*/\1/'
}

lock_screen() {
  resolution=$(get_resolution)
  convert ~/.config/i3lock/stop.png -gravity center -background black -extent $resolution ~/.config/i3lock/centered_stop.png
  i3lock -c 000000 -i ~/.config/i3lock/centered_stop.png
}

lock_screen
