#!/bin/bash

# additional settings

wallpape="$HOME/.config/bspwm/img/kali.png
feh --bg-fill "$wallpape" || hsetroot -solid '#121212'

hsetroot -solid '#121212'

### Mouse and Touchpad Settings
# TrackPoint settings
xinput set-prop 'TPPS/2 IBM TrackPoint' 'libinput Accel Speed' -0.6 &

# Touchpad settings for T450
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Accel Speed' -0.1 &
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Scroll Method Enabled' 0 1 0 &
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Horizontal Scroll Enabled' 1 &
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Natural Scrolling Enabled' 0 &
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1 &

# Disable touchpad while typing
xinput set-prop 'SynPS/2 Synaptics TouchPad' "libinput Disable While Typing Enabled" 1 &
#syndaemon -i 2.0 -d

### System Settings
# Disable beep sound
xset -b

# Keyboard repeat rate
xset r rate 150 25

# Enable DPMS (timeouts in seconds)
# this setting doesn't suspend or shutdowns the system only the display
xset dpms 150 300 600 # display-dims, display turns off, display powered off

### Process Management

# Improved function to restart processes with arguments
restart_process() {
  local process_name="$1"
  local cmd="$@"

  # Kill by full command (including arguments)
  pkill -f -e "$cmd" || true
  sleep 0.1
  # Start the process
  $cmd &
}

# In your autostart script, before restarting processes:
pkill -f "xss-lock.*slock" || true # Force-kill existing instances
pkill -f xfce4-notifyd || true#

# Define processes (use quotes for commands with arguments)
process_list=(
  #  "kdeconnectd"
  #  "kdeconnect-indicator"
  "lxpolkit"
  "xfce4-clipman"
  "nm-applet"
  "dunst"
  "sxhkd"
  "polybar -q -r main -c ~/.config/polybar/config.ini"
  "lxde-settings-daemon"
  "xss-lock --ignore-sleep -- slock" # Add --ignore-sleep for robustness
  "xfce4-notes"
#  "picom"
  "xbindkeys"
)

Restart each process
for process in "${process_list[@]}"; do
  restart_process $process
done

redshift -x ; redshift -P -O 2500
